name: tinc
version: 0.1.0
category: Development
license: "BSD3"
author: "Sönke Hahn"
copyright: "Sönke Hahn"
maintainer: "soenke.hahn@zalora.com"
github: soenkehahn/tinc

ghc-options: -Wall

dependencies:
  - base == 4.*
  - base-compat
  - graph-wrapper >= 0.2.5
  - language-dot
  - containers
  - directory
  - filepath
  - process >= 1.2
  - parsec
  - temporary

source-dirs: src

executables:
  tinc:
    main: tinc.hs
    source-dirs: driver

tests:
  spec:
    main: "Spec.hs"
    source-dirs: test

    dependencies:
      - hspec
      - hspec-expectations
      - mockery
      - silently
      - shelly
