#!/bin/sh
set -o nounset
set -o errexit

SANDBOX=$(mktemp -d "${TMPDIR:-/tmp}"/tinc-XXXX)
trap "rm -rf $SANDBOX" EXIT

if [ $# -eq 0 ]; then
  tarball=$(cabal sdist | grep -o "\S*\.tar\.gz")
  cp $tarball  $SANDBOX
  cd $SANDBOX
  tar xvf *.tar.gz
elif [ $# -eq 1 ]; then
  cd $SANDBOX
  cabal unpack $1
else
  >&2 echo "usage: tinc install [PACKAGE]"
  exit 1
fi

cd *
tinc


# NOTE: This is technically not necessary as we already ensure in Tinc.Facts
# that TINC_USE_NIX is always set.  We default TINC_USE_NIX to "no" here anyway
# to give a smoother upgrade path, but it can and should be removed eventually.
TINC_USE_NIX=${TINC_USE_NIX:-no}


if [ "$TINC_USE_NIX" = "yes" ]; then
  find . -exec touch -d "1970-01-01 00:00:00 UTC" {} \;
  NAME=`sed -rn '/pname/ s/.*"(.*)";/\1/p' package.nix`
  nix-env -i "$NAME" -f default.nix
else
  cabal install --prefix ~/.tinc ${1:-} # we pass $1 here, as a workaround for https://github.com/haskell/cabal/issues/4593
fi
